<a href="https://colab.research.google.com/github/Ahtesham-Ibne-Mostafa/Dataset_Genesis/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy
import numpy as np

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
array=np.array([1,2,3,4])

In [ ]:
# Reshape the 1D array to a 2D array
array = np.arange(1, 7).reshape((2, 3))
 
print(array)

[[1 2 3]
 [4 5 6]]


In [ ]:
array=np.ones((1, 2, 3))
print(array)

[[[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
array = np.arange(24)

new_array = array.reshape((2, 3, 4))

print(new_array)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
array = np.linspace(0, 1, 50)

print(array)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [ ]:
array = numpy.arange(30)

new_array = array.reshape((3, 2, 5))

print(new_array)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
array = numpy.arange(1,41).reshape(5,2,4)

depth , rows, cols = array.shape

middle_dep = depth //2

middle_col = cols //2


array[middle_dep, :, middle_col] = 0
array[middle_dep, :, middle_col-1] = 0

print(array)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17  0  0 20]
  [21  0  0 24]]

 [[25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]]]


In [64]:
array = numpy.arange(100).reshape(5,2,2,5)

array[array % 10 == 0] = 0

print(array)

[[[[ 0  1  2  3  4]
   [ 5  6  7  8  9]]

  [[ 0 11 12 13 14]
   [15 16 17 18 19]]]


 [[[ 0 21 22 23 24]
   [25 26 27 28 29]]

  [[ 0 31 32 33 34]
   [35 36 37 38 39]]]


 [[[ 0 41 42 43 44]
   [45 46 47 48 49]]

  [[ 0 51 52 53 54]
   [55 56 57 58 59]]]


 [[[ 0 61 62 63 64]
   [65 66 67 68 69]]

  [[ 0 71 72 73 74]
   [75 76 77 78 79]]]


 [[[ 0 81 82 83 84]
   [85 86 87 88 89]]

  [[ 0 91 92 93 94]
   [95 96 97 98 99]]]]


In [66]:
array = np.arange(24).reshape(3, 2, 4)

new_array = array[array % 2 != 0]

print("Original array:")
print(array)

print("\nNew array with odd numbers:")
print(new_array)

Original array:
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]

New array with odd numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23]


NumPy arrays provide a fast and convenient way to perform mathematical operations on large sets of data. They support element-wise operations, vectorization, and broadcasting, allowing efficient computations on arrays of different shapes and sizes. Powerful tools for slicing, indexing, and aggregating data, making it easy to extract and analyze specific subsets of data.

NumPy arrays provide a foundation for linear algebra operations. They can represent vectors, matrices, and higher-dimensional tensors, enabling efficient computations such as matrix multiplication, eigenvalue calculation, and solving linear equations.

Images can be represented as multi-dimensional arrays, and NumPy provides functions to manipulate, transform, and analyze images efficiently.

Can represent audio signals, time series data, or any other signal type. NumPy provides functions for signal filtering, Fourier transforms, convolution, and more.

Numpy can only store elements of the same data type. In contrast, Python lists can contain elements of different data types.
NumPy arrays are more memory-efficient compared to Python lists. 
NumPy arrays offer better performance for numerical operations and computations compared to Python lists.
NumPy arrays come with a wide range of built-in functions and methods for mathematical operations, array manipulation, and linear algebra. Python lists have a more limited set of built-in functions and methods.
The wider SciPy ecosystem, includes NumPy as a component. Libraries for data visualization, machine learning, optimization, and other topics are included in this ecosystem. This robust infrastructure designed for scientific computing does not exist in Python lists.